config/routes.rb
Rails.application.routes.draw do
  resources :logs
  resources :categories
  resources :items do 
    resources :logs, only: [:index, :show, :new, :edit, :create]
    resources :categories, only: [:index, :show, :new, :edit, :create]
  end
  
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'past_due', to: "logs#past_due"
  get 'upcoming', to: "logs#upcoming"

  get 'logs/:id/log_data', to: 'logs#log_data'

  root "items#index"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :logs
  has_many :categories
  validates :name, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

	def index
		if current_user
			@items = current_user.items
		else
			redirect_to sign_in_path
		end

	end

	def new
		@item = Item.new
	end

	def create
		@item = current_user.items.build(item_params)
		if @item.save
			redirect_to item_path(@item)
		else
			render :new
		end
	end

	def update
		@item.update(item_params)
		redirect_to item_path(@item)
	end

	def destroy 
		@item.destroy
		redirect_to items_path
	end

	def show
		#for use with form to make a new log
		#@log = @item.logs.build
	end

	def edit
	end

	private

	def set_item 
		@item = Item.find(params[:id])
	end

	def item_params
		params.require(:item).permit(:name, :user_id)
	end


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:
    </h2>

    <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
        <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @item, :html => {:class => "form-group"} do |f| %>
  
  <%= f.text_field :name, :class => 'form-control', :placeholder => "Enter New Maintenance Item Name" %><br>

  <%= f.submit class:'btn btn-primary' %>
<% end %>

app/views/items/edit.html.erb
<h3>Edit <%= @item.name %></h3>

<%= render 'form' %>

app/views/items/index.html.erb
<h3>Maintenance Items</h3>
<div class="list-group">
  <% @items.each do |item| %>
    <li class="d-flex align-items-start flex-md-row">
      <span class="badge badge-primary badge-pill">
        <%= item.logs.past_due.count %>
      </span>
      <%= link_to item.name, item_path(item), html_options = {class: 'list-group-item list-group-item-action list-group-item-light'} %>

      <%= link_to  "Show Categories", item_categories_path(item), id: "catBtn_#{item.id}", class: 'btn align-self-center badge badge-primary' %>

      <%= link_to  "Delete this item", item, method: :delete, data: { confirm: 'Are you sure about that?'}, class: 'btn align-self-center badge badge-primary' %>
    </li>
    
    <br>
    <div class="accordion">
      <div id="<%= "showCategory_#{item.id}" %>"></div>
    </div>
  <% end %>
</div>
<br>
<%= link_to 'Add New Maintenance Item', new_item_path, html_options = {class: 'badge badge-primary'} %>

app/views/items/new.html.erb
<h3>Add a New Maintenance Item</h3>

<%= render 'form' %>

<%= link_to 'Back', items_path, html_options = {class: 'badge badge-primary'} %><br>

app/views/items/show.html.erb
<h3>Maintenance Categories for <%= @item.name %> </h3> 

<%= link_to  "Edit #{@item.name}", edit_item_path(@item), html_options = {class: 'badge badge-dark'} %><br>
<br>

<div class="list-group">
  <% @item.categories.uniq.each do |category| %>
    <li class="d-flex align-items-start flex-md-row">
      <span class="badge badge-primary badge-pill">
        <%= category.logs.past_due.count %>
      </span>
      <%= link_to  category.name, item_category_path(@item, category), html_options = {class: 'list-group-item list-group-item-action list-group-item-light'} %>

      <%= link_to  "Show Logs", item_category_path(@item, category), id: "logBtn_#{category.id}" ,class: 'btn align-self-center badge badge-primary' %>
    </li>
    <br>
    <div class="accordion" >
      <div id="<%= "showLog_#{category.id}" %>"></div>
    </div>
  <% end %>
</div>
<br>

<%= link_to  "Back To Items", items_path, html_options = {class: 'badge badge-primary'} %><br>
<%= link_to  "Add a Category", new_item_category_path(@item), html_options = {class: 'badge badge-primary'} %><br>
<%= link_to  "Add a New Log", new_item_log_path(@item), html_options = {class: 'badge badge-primary'} %><br>