config/routes.rb
Rails.application.routes.draw do
  resources :logs
  resources :categories
  resources :items do 
    resources :logs, only: [:index, :show, :new, :edit, :create]
    resources :categories, only: [:index, :show, :new, :edit, :create]
  end
  
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'past_due', to: "logs#past_due"
  get 'upcoming', to: "logs#upcoming"

  get 'logs/:id/log_data', to: 'logs#log_data'

  root "items#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :item
  has_many :logs
  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    if params[:item_id]
      @item = Item.find_by(id: params[:item_id])
      if @item.nil?
        redirect_to item_path, alert: "That Maintenance Item Does Not Exist"
      else
        @categories = @item.categories
      end
    else 
      @categories = Category.all
    end

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @categories }
    end
  end

  def new
    if params[:item_id] && !Item.exists?(params[:item_id])
      redirect_to item_path, alert: "Item not found"
    else
      @item = Item.find(params[:item_id])
      @category = @item.categories.build
    end
  end
  
  def create
    if params[:item_id] && !Item.exists?(params[:item_id])
      redirect_to item_path, alert: "Item not found"
    else
      @item = Item.find(params[:item_id])
      if @category = @item.categories.find_or_create_by(category_params)
        redirect_to item_category_path(@item, @category)
      else
        render :new
      end
    end
  end

  def update
    @category = Category.find(params[:id])
    @category.update

    if @category.save
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    redirect_to :root
  end

  def show
    if params[:item_id]
      @item = Item.find_by(id: params[:item_id])
      @category = @item.categories.find_by(id: params[:id])
      #for JSON
      @logs = @category.logs
      if @category.nil?
        #should this be item_path?
        redirect_to item_category_path(@item), alert: "Category not found"
      end
    else
      @category = Category.find(params[:id])
    end

    respond_to do |format|
      format.html { render :show}
      format.json { render json: @logs}
    end

  end

  def edit
    if params[:item_id]
      item = Item.find_by(id: params[:item_id])
      if item.nil?
        redirect_to item_path, alert: "item not found"
      else
        @category = item.categories.find_by(id: params[:id])
        redirect_to item_categories_path, alert: "category not found"
      end 
    else
      @category = Category.find(params[:id])
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :item_id)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:
    </h2>

    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
        <% end %>
    </ul>
  </div>
<% end %>
<%= form_for [@item, @category], :html => {:class => "form-group"} do |f| %>
  
  <%= f.text_field :name, :class => 'form-control', :placeholder => "Enter New Category Name" %><br>

  <%= f.submit class: 'btn btn-primary' %><br>

<% end %>

app/views/categories/edit.html.erb
<h3>Edit <%= @category.name %></h3>

<%= render 'form' %>

app/views/categories/new.html.erb
<h3>Make a New Category</h3>

<%= render 'form' %>
<br>
<%= link_to  "Back to Maintenance Categories", item_path(@item), html_options = {class: 'badge badge-primary'} %><br>

app/views/categories/show.html.erb
<h3>Logs for <%= @category.name %></h3>

<%= link_to  "Edit #{@category.name}", edit_category_path(@category), html_options = {class: 'badge badge-dark'} %><br>
<br>

<div <li class="list-group"> 
  <%= @category.logs.each do |log| %>
    <% unless log.date_performed.nil? %>
      <li class="d-flex align-items-start flex-md-row">
        <%= link_to  "Performed on #{formatted_date_performed(log)}" , log_path(log), html_options = {class: 'list-group-item list-group-item-action list-group-item-light'} %>

        <%= link_to  "Show Details", log_path(log), id: "detailsBtn_#{log.id}" ,class: 'btn align-self-center badge badge-primary' %>
      </li>
      <br>
      <div class="accordion" >
        <div id="<%= "showDetails_#{log.id}" %>"></div>
      </div>
    <% end %>
  <% end %>
</div>
<br>

<%= link_to "Back to #{@item.name}", item_path(@item), html_options = {class: 'badge badge-primary'} %><br>
<%= link_to  "Add a new log entry", new_item_log_path(@item), html_options = {class: 'badge badge-primary'} %>