config/routes.rb
Rails.application.routes.draw do
  resources :logs
  resources :categories
  resources :items do 
    resources :logs, only: [:index, :show, :new, :edit, :create]
    resources :categories, only: [:index, :show, :new, :edit, :create]
  end
  
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'past_due', to: "logs#past_due"
  get 'upcoming', to: "logs#upcoming"

  get 'logs/:id/log_data', to: 'logs#log_data'

  root "items#index"
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :item
  belongs_to :category
  validates :cost, numericality: true
  validates :category, presence: true
  validate :starts_after_today?, :due_before_start?

  def category_attributes=(attributes)
    #ensures that radio button only used if text field left empty
    # if attributes[:name].empty?
    #   category = Category.find_by(id: attributes[:id])
    # else
    #   category = Category.find_or_create_by(name: attributes[:name])
    # end
    category = Category.find_by(id: attributes[:id])
    self.category = category
  end

  def starts_after_today?
    if date_performed.present? && date_performed > Date.today 
      errors.add(:date_performed, "can't be in the future")
    end
  end

  def due_before_start?
    if date_due.present? && date_due < date_performed
      errors.add(:date_due, "can't be before the performed date")
    end
  end

  def category_blank?(att)
    att['name'].blank?
  end

  def self.past_due
    where("date_due <=?", Time.current)
  end

  def self.upcoming
    where("date_due <=?", Time.current + 30.days)
  end

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

  def index
    if params[:category_id]
      @category = Category.find_by(id: params[:category_id])
      if @category.nil?
        redirect_to category_path, alert: "That category doesn't exist"
      else
        @logs = @category.logs
      end
    else
      @logs = Log.all
    end
  end

  def new
    if params[:item_id] && !Item.exists?(params[:item_id])
      redirect_to :root, alert: "That item doesn't exist"
    else
      @item = Item.find(params[:item_id])
      @log = @item.logs.build
    end
  end

  def create
    if params[:item_id] && !Item.exists?(params[:item_id])
      redirect_to item_path, alert: "That item doesn't exist"
    else
      @item = Item.find(params[:item_id])
      @log = @item.logs.create(log_params)
      if @log.valid?
        respond_to do |format|
          format.html { redirect_to item_log_path(@item, @log) }
          format.json { render json: @log }
        end
      else
        render :new
      end
    end
  end

  def show
    if params[:category_id]
      @category = Category.find_by(id: params[:category_id])
      @log = @category.logs.find_by(id: params[:id])
      if @log.nil?
        redirect_to category_log_path(@category), alert: "Log not found"
      end
    else
      @log = Log.find(params[:id])
    end

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @log }
    end
  end

  def update
    @log = Log.find(params[:id])
    @log.update(log_params)
    if @log.save
      redirect_to log_path(@log)
    else
      render :edit
    end
  end

  def edit
    if params[:category_id]
      category = Category.find_by(id: params[:category_id])
      if category.nil?
        redirect_to category_path, alert: "Category not found"
      else
        @log = category.logs.find_by(id: params[:id])
        redirect_to category_logs_path, alert: "Log not found"
      end
    else
      @log = Log.find(params[:id])
    end
  end

  def destroy
    Log.find(params[:id]).destroy
    redirect_to :root
  end

  def past_due
    @current_user_logs = []
    @items = current_user.items
    @items.each do |item|
      item.logs.past_due.each do |log|
        @current_user_logs << log
      end
    end
  end

  def upcoming
    @current_user_logs = []
    @items = current_user.items
    @items.each do |item|
      item.logs.upcoming.each do |log|
        @current_user_logs << log
      end
    end
  end

  

  private

  def log_params
    params.require(:log).permit(:notes, :tools, :cost, :date_performed, :date_due, :category_id, :item_id, category_attributes: [:name, :id])
  end

end

app/helpers/logs_helper.rb
module LogsHelper

  def formatted_date_performed(log)
    log.date_performed.strftime("%b %d, %Y")
  end

  def formatted_date_due(log)
    log.date_due.strftime("%b %d, %Y")
  end
end

app/views/logs/_form.html.erb
<% if @log.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@log.errors.count, "error") %> prohibited this log from being saved:
    </h2>
    
    <ul>
      <% @log.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [@item, @log], :html => {:class => "form-group"} do |f| %>

  <div class="form-group col-auto">
    <p>Select a Category</p>
    <%= f.fields_for :category, @log.build_category do |category| %>
      <%= category.collection_radio_buttons :id, @item.categories, :id, :name %><br>
      <%# <%= category.text_field :name, :class => 'form-control', :placeholder => "Add a New Category" %>
    <% end %>
  </div>

  <div class="form-group col-auto">
    <%= f.label :date_performed %>
    <%= f.date_select :date_performed, :class => 'form-control' %><br>
    <%= f.label :date_due, :class => '' %>
    <%= f.date_select :date_due, :class => 'form-control' %><br>
  </div>

  <div class="form-group col-auto">
    <%= f.label :tools %>
    <%= f.text_field :tools, :class => 'form-control', :placeholder => "Enter Tools" %>
  </div>

  <div class="form-group col-auto">  
  <%= f.label :cost %>
  <%= f.number_field :cost, :class => 'form-control', :placeholder => "Enter Cost" %>
  </div>

  <div class="form-group col-auto">  
  <%= f.label :notes %>
  <%= f.text_area :notes, :class => 'form-control', :placeholder => "Enter Any Notes" %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/logs/edit.html.erb
<h3 class='col-auto'>Edit</h3>

<%= render 'form' %>

app/views/logs/new.html.erb
<h3>Add a New Log for <%= @log.item.name %></h3>

<%= render 'form' %>

<div id="logResult">
  <p id="logDatePerformed"></p>
  <p id="logDateDue"></p>
  <p id="logCost"></p>
  <p id="logNotes"></p>
  <p id="logTools"></p>
</div>

<%= link_to  "Back to Logs for #{@log.item.name}", item_path(@log.item_id), html_options = {class: 'badge badge-primary'} %><br>

app/views/logs/past_due.html.erb
<h3>Past Due</h3>

<% if @current_user_logs.any? %>
  <%= @current_user_logs.each do |log| %>
    <%= link_to  "#{log.category.name} Was due on #{formatted_date_due(log)}", log_path(log) %><br>
  <% end %>
<% else %>
  <p>You're an adequate mechanic, nothing is past due</p>
<% end %>

app/views/logs/show.html.erb
<div class="form-group">
  <%# <h3>Log for <%= @log.category.name</h3> %>

  <div class="col-auto">
    <h5>Date Performed:</h5>
    <% if @log.date_performed %>
      <%= formatted_date_performed(@log) %><br>
    <% else %>
      No Date Entered
    <% end %>
  </div>
  <br>

  <div class="col-auto">
    <h5>Date due:</h5>
    <% if @log.date_due %>
      <%= formatted_date_due(@log) %><br>
    <% else %>
      No Date Entered
    <% end %>
  </div>
  <br>

  <div class="col-auto">
    <h5>Tools Required:</h5>
    <%= @log.tools %><br>
  </div>
  <br>

  <div class="col-auto">
    <h5>Cost:</h5>
    $<%= @log.cost %><br>
  </div>
  <br>

  <div class="col-auto">
    <h5>Notes:</h5>
    <%= @log.notes %><br>
  </div>
  <br>
  
  <div class="col-auto">
    <%= link_to  "Back to Logs for #{@log.item.name}", item_path(@log.item_id), html_options = {class: 'badge badge-primary'} %><br>
    <%= link_to  "Edit", edit_item_log_path(@log.item_id, @log), html_options = {class: 'badge badge-primary'} %><br>
    <%= link_to  "Delete this log entry", @maintenance_log, method: :delete, data: { confirm: "You sure?"}, class: "badge badge-primary" %><br>
    <%= link_to  "Add a New Entry", new_item_log_path(@log.item_id), html_options = {class: 'badge badge-primary'} %><br>
  </div>
</div>

app/views/logs/upcoming.html.erb
<h3>Upcoming Work</h3>

<% if @current_user_logs.any? %>
  <%= @current_user_logs.each do |log| %>
    <%= link_to  "#{log.category.name} Will be due on #{formatted_date_due(log)}", log_path(log) %><br>
  <% end %>
<% else %>
  <p>Enjoy the break, you don't have anything to do for the next month</p>
<% end %>